- name: Configure Jitsi Meet config files for host login
  hosts: localhost
  become: yes
  gather_facts: yes

  tasks:
  - name: Grepping hostname from JVB config
    shell: grep JVB_HOSTNAME= /etc/jitsi/videobridge/config | sed 's/^.*=//'
    register: domain_name

  - name: Configure Jicofo
    lineinfile:
      path: /etc/jitsi/jicofo/sip-communicator.properties
      line: org.jitsi.jicofo.auth.URL=XMPP:{{ domain_name.stdout }}
      state: present

  - name: Make Host Login Prosody
    lineinfile:
      path: /etc/prosody/conf.avail/{{ domain_name.stdout}}.cfg.lua
      insertafter: 'VirtualHost "{{ domain_name.stdout }}"'
      regexp: '        authentication = '
      line: '        authentication = "internal_hashed"'

  - name: Enable anonymous login method for guests
    blockinfile:
      path: /etc/prosody/conf.avail/{{ domain_name.stdout}}.cfg.lua
      marker: "-- {mark} Ansible managed anonymous login"
      state: present
      block: |
        VirtualHost "guest.{{ domain_name.stdout }}"
            authentication = "anonymous"
            modules_enabled = {
              "turncredentials";
            }
            c2s_require_encryption = false

  - name: Make Host Login Jitsi-Meet - anonymousdomain
    lineinfile:
      path: /etc/jitsi/meet/{{ domain_name.stdout }}-config.js
      insertafter: "^(\ *)domain: '{{ domain_name.stdout }}',"
      regexp: '^(\ *)anonymousdomain:'
      line: "        anonymousdomain: 'guest.{{ domain_name.stdout }}',"

  - name: Make Host Login Jitsi-Meet - authdomain
    lineinfile:
      path: /etc/jitsi/meet/{{ domain_name.stdout }}-config.js
      insertafter: "        anonymousdomain: 'guest.{{ domain_name.stdout }}',"
      regexp: '^(\ *)authdomain:'
      line: "        authdomain: '{{ domain_name.stdout }}',"

  - name: Configure System Config.
    lineinfile:
      path: /etc/systemd/system.conf
      regexp: "{{ item.regexp }}"
      line: "{{ item.line }}"
      state: present
    with_items:
      - { regexp: '^DefaultLimitNOFILE', line: 'DefaultLimitNOFILE=65000'}
      - { regexp: '^DefaultLimitNPROC', line: 'DefaultLimitNPROC=65000'}
      - { regexp: '^DefaultTasksMax', line: 'DefaultTasksMax=65000'}

# https://stackoverflow.com/questions/39819378/ansible-get-current-target-hosts-ip-address
  - name: Configure behind a NAT.  First set local IP
    lineinfile:
      path: /etc/jitsi/videobridge/sip-communicator.properties
      regexp: '^org.ice4j.ice.harvest.NAT_HARVESTER_LOCAL_ADDRESS='
      line: "org.ice4j.ice.harvest.NAT_HARVESTER_LOCAL_ADDRESS={{ ansible_default_ipv4.address }}"

  - name: Get the ip address of the domain.
    shell: 'dig \+short "{{ domain_name.stdout }}"; echo'
    register: host_ip

  - name: Configure behind a NAT.  Now set host domain IP
    lineinfile:
      path: /etc/jitsi/videobridge/sip-communicator.properties
      regexp: '^org.ice4j.ice.harvest.NAT_HARVESTER_PUBLIC_ADDRESS='
      line: "org.ice4j.ice.harvest.NAT_HARVESTER_PUBLIC_ADDRESS={{ host_ip.stdout }}"

  - name: Comment out
    lineinfile:
      path: /etc/jitsi/videobridge/sip-communicator.properties
      regexp: 'org.ice4j.ice.harvest.STUN_MAPPING_HARVESTER_ADDRESSES'
      line: "#org.ice4j.ice.harvest.STUN_MAPPING_HARVESTER_ADDRESSES"
