- name: Configure files for OpenSSH
  hosts: localhost
  become: yes

  tasks:                                                                 
  - name: OpenSSH update Key exchange algorithms to Mozilla recommendations.
    lineinfile:
      path: /etc/ssh/ssh_config
      regexp: 'KexAlgorithms'
      line: 'KexAlgorithms curve25519-sha256@libssh.org,ecdh-sha2-nistp521,ecdh-sha2-nistp384,ecdh-sha2-nistp256,diffie-hellman-group-exchange-sha256'
      state: present

  - name: OpenSSH Supported HostKey algorithms by order of preference.
    blockinfile:
      path: /etc/ssh/ssh_config
      marker: "# {mark} Ansible managed HostKey and AuthenticationMethods"
      insertafter: '#HostKey /etc/ssh/ssh_host_ed25519_key'
      state: present
      block: |
        HostKey /etc/ssh/ssh_host_ed25519_key
        HostKey /etc/ssh/ssh_host_rsa_key
        HostKey /etc/ssh/ssh_host_ecdsa_key
        AuthenticationMethods publickey
