- name: Turn off logging.
  hosts: localhost
  become: yes

  tasks:
  - name: Turn off logging by coturn
    lineinfile:
      path: /etc/turnserver.conf
      regexp: "{{ item.regexp }}"
      line: "{{ item.line }}"
      state: present
    with_items:
      - { regexp: 'log-file=/dev/null', line: 'log-file=/dev/null'}
      - { regexp: 'simple-log', line: 'simple-log'}
      - { regexp: 'no-stdout-log', line: 'no-stdout-log'}

  - name: Remvove syslog in turnserver.conf
    lineinfile:
      path: /etc/turnserver.conf
      regexp: 'syslog'
      state: absent

  - name: Turn off Access logs in nginx (way to do it in 1.14.0+)
    lineinfile:
      path: /etc/nginx/nginx.conf
      regexp: 'access_log'
      line: "\taccess_log off;"
      state: present

#  - name: Send Error logs in nginx to /dev/null
#    lineinfile:
#      path: /etc/nginx/nginx.conf
#      regexp: 'error_log'
#      line: "\terror_log /dev/null;"
#      state: present

  - name: Turn off info logs in prosody, send them to /dev/null
    lineinfile:
      path: /etc/prosody/prosody.cfg.lua
      regexp: '\tinfo = '
      line: '\tinfo = "/dev/null";'
      state: present

# Leave on for a quick check.
#  - name: Turn off error logs in prosody, send them to /dev/null
#    lineinfile:
#      path: /etc/prosody/prosody.cfg.lua
#      regexp: '\terror = '
#      line: '\terror = "/dev/null";'
#      state: present
